exclude: >
  (?x)^(
      \.eggs|
      \.git|
      \.mypy_cache|
      \.tox|
      \.pyre_configuration|
      \.venv|
      build|
      dist|
      src/findpython/_vendor/.*\.py
  )$

repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
